FROM traefik:latest

COPY traefik.yml /etc/traefik/traefik.yml
COPY config.yml /etc/traefik/config.yml
#COPY certs/test_api_example.cert /etc/certs/test_api_example.cert
#COPY certs/test_api_example.key /etc/certs/test_api_example.key